workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean project
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: List IPA Directory
        script: ls -l build/ios/ipa/
    artifacts:
      - build/ios/ipa/hhh.ipa 

    publishing:
      email:
        recipients:
          - navneetjha190@gmail.com
